# Generated by Django 4.1 on 2023-12-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.TextField()),
                ("course_by", models.TextField()),
                ("title", models.TextField()),
                ("skills", models.TextField()),
                ("ratings", models.FloatField()),
                ("reviews", models.TextField()),
                ("level", models.TextField()),
                ("type", models.TextField()),
                ("duration", models.TextField()),
            ],
        ),
    ]
